[package]
name = "marmalade"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.51"
argon2 = { version = "0.3.1", features = ["std"] }
askama = { version = "0.10.5", default-features = false, features = ["urlencode"] }
axum = { version = "0.4.0", features = ["headers", "http2"] }
camino = "1.0.5"
cookie = { version = "0.16.0-rc.1", features = ["private"] }
directories-next = "2.0.0"
futures-util = "0.3.18"
git2 = { version = "0.13.25", default-features = false }
headers = "0.3.5"
hex = "0.4.3"
mime = "0.3.16"
once_cell = "1.8.0"
percent-encoding = "2.1.0"
pulldown-cmark = { version = "0.8.0", default-features = false }
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
syntect = "4.6.0"
tokio = { version = "1.14.0", features = ["macros", "fs", "process", "rt", "signal", "sync"] }
tokio-util = { version = "0.6.9", features = ["io"] }
tower = "0.4.11"
tower-http = { version = "0.2.0", features = ["compression-gzip", "decompression-gzip", "trace"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
whoami = "1.2.1"

[dev-dependencies]
serde_test = "1.0.130"

[build-dependencies]
indoc = "1.0.3"
proc-macro2 = "1.0.32"
quote = "1.0.10"
sass-rs = "0.2.2"
syntect = "4.6.0"

[profile.release]
lto = true
