[package]
name = "marmalade"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.44"
argon2 = { version = "0.3.1", features = ["std"] }
askama = { version = "0.10.5", default-features = false, features = ["urlencode"] }
axum = { version = "0.3.0", features = ["headers", "http2"], git = "https://github.com/tokio-rs/axum.git", rev = "a2627e9084f86a9eab28c2d5463884ee37dcfeca" }
camino = "1.0.5"
cookie = { version = "0.16.0-rc.1", features = ["private"] }
directories-next = "2.0.0"
futures-util = "0.3.17"
git2 = { version = "0.13.23", default-features = false }
headers = "0.3.5"
hex = "0.4.3"
mime = "0.3.16"
once_cell = "1.8.0"
percent-encoding = "2.1.0"
pulldown-cmark = "0.8.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
syntect = "4.6.0"
tokio = { version = "1.12.0", features = ["macros", "fs", "process", "rt", "signal", "sync"] }
tokio-util = { version = "0.6.8", features = ["io"] }
toml = "0.5.8"
tower = "0.4.10"
tower-http = { version = "0.1.1", features = ["compression-gzip", "decompression-gzip", "trace"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
whoami = "1.1.5"

[profile.release]
lto = true

[build-dependencies]
indoc = "1.0.3"
proc-macro2 = "1.0.32"
quote = "1.0.10"
sass-rs = "0.2.2"
syntect = "4.6.0"
