[package]
name = "marmalade"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.75"
argon2 = { version = "0.5.2", features = ["std"] }
askama = { version = "0.12.0", default-features = false, features = ["urlencode", "with-axum"] }
askama_axum = "0.3.0"
axum = { version = "0.6.20", features = ["headers", "http2"] }
camino = "1.1.6"
cookie = { version = "0.17.0", features = ["private"] }
futures-util = "0.3.28"
git2 = { version = "0.17.2", default-features = false }
headers = "0.3.9"
hex = "0.4.3"
mime = "0.3.17"
once_cell = "1.18.0"
percent-encoding = "2.3.0"
pulldown-cmark = { version = "0.9.3", default-features = false }
rand = "0.8.5"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
syntect = "5.1.0"
tokio = { version = "1.32.0", features = ["macros", "fs", "process", "rt-multi-thread", "sync"] }
tokio-shutdown = "0.1.4"
tokio-util = { version = "0.7.8", features = ["io"] }
tower = "0.4.13"
tower-http = { version = "0.4.4", features = ["compression-gzip", "decompression-gzip", "trace", "util"] }
tracing = "0.1.37"
tracing-archer = { git = "https://github.com/dnaka91/archer.git" }
tracing-subscriber = "0.3.17"
unidirs = "0.1.1"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
whoami = "1.4.1"

[dev-dependencies]
serde_test = "1.0.176"

[build-dependencies]
grass = { version = "0.13.1", default-features = false }
proc-macro2 = "1.0.66"
quote = "1.0.33"
syntect = "5.1.0"

[profile.release]
lto = true
strip = true
