[package]
name = "marmalade"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.71"
argon2 = { version = "0.5.0", features = ["std"] }
askama = { version = "0.12.0", default-features = false, features = ["urlencode", "with-axum"] }
askama_axum = "0.3.0"
axum = { version = "0.6.18", features = ["headers", "http2"] }
camino = "1.1.4"
cookie = { version = "0.17.0", features = ["private"] }
futures-util = "0.3.28"
git2 = { version = "0.17.1", default-features = false }
headers = "0.3.8"
hex = "0.4.3"
mime = "0.3.17"
once_cell = "1.17.1"
percent-encoding = "2.2.0"
pulldown-cmark = { version = "0.9.2", default-features = false }
rand = "0.8.5"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
syntect = "5.0.0"
tokio = { version = "1.28.0", features = ["macros", "fs", "process", "rt-multi-thread", "sync"] }
tokio-shutdown = "0.1.3"
tokio-util = { version = "0.7.8", features = ["io"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["compression-gzip", "decompression-gzip", "trace", "util"] }
tracing = "0.1.37"
tracing-archer = { git = "https://github.com/dnaka91/archer.git" }
tracing-subscriber = "0.3.17"
unidirs = "0.1.1"
uuid = { version = "1.3.2", features = ["serde", "v4"] }
whoami = "1.4.0"

[dev-dependencies]
serde_test = "1.0.160"

[build-dependencies]
grass = { version = "0.12.3", default-features = false }
proc-macro2 = "1.0.56"
quote = "1.0.26"
syntect = "5.0.0"

[profile.release]
lto = true
strip = true
