[package]
name = "marmalade"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.57"
argon2 = { version = "0.4.0", features = ["std"] }
askama = { version = "0.11.2", git = "https://github.com/djc/askama.git", default-features = false, features = ["urlencode", "with-axum"] }
askama_axum = { version = "0.1.0", git = "https://github.com/djc/askama.git" }
axum = { version = "0.5.6", features = ["headers", "http2"] }
camino = "1.0.9"
cookie = { version = "0.16.0", features = ["private"] }
futures-util = "0.3.21"
git2 = { version = "0.14.4", default-features = false }
headers = "0.3.7"
hex = "0.4.3"
mime = "0.3.16"
once_cell = "1.12.0"
percent-encoding = "2.1.0"
pulldown-cmark = { version = "0.9.1", default-features = false }
rand = "0.8.5"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
syntect = "5.0.0"
tokio = { version = "1.18.2", features = ["macros", "fs", "process", "rt-multi-thread", "sync"] }
tokio-shutdown = "0.1.0"
tokio-util = { version = "0.7.2", features = ["io"] }
tower = "0.4.12"
tower-http = { version = "0.3.3", features = ["compression-gzip", "decompression-gzip", "trace"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
unidirs = "0.1.0"
uuid = { version = "1.0.0", features = ["serde", "v4"] }
whoami = "1.2.1"

[dev-dependencies]
serde_test = "1.0.137"

[build-dependencies]
indoc = "1.0.6"
proc-macro2 = "1.0.39"
quote = "1.0.18"
sass-rs = "0.2.2"
syntect = "5.0.0"

[profile.release]
lto = true
strip = true
