[package]
name = "marmalade"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.44"
argon2 = { version = "0.3.1", features = ["std"] }
askama = { version = "0.10.5", default-features = false }
axum = { version = "0.2.4", features = ["http2"] }
camino = "1.0.5"
cookie = { version = "0.16.0-rc.1", features = ["private"] }
directories-next = "2.0.0"
futures-util = "0.3.17"
git2 = { version = "0.13.22", default-features = false }
hex = "0.4.3"
once_cell = "1.8.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
tokio = { version = "1.11.0", features = ["macros", "fs", "process", "rt", "signal", "sync"] }
tokio-util = { version = "0.6.8", features = ["io"] }
toml = "0.5.8"
tower = "0.4.8"
tower-http = { version = "0.1.1", features = ["compression-gzip", "decompression-gzip", "trace"] }
tracing = "0.1.27"
tracing-subscriber = "0.2.22"
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[profile.release]
lto = true
