[advisories]
ignore = ["RUSTSEC-2024-0320"]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "marmalade" },
]

[bans]
skip = [
    "base64@0.21",
    "bitflags@1",
    "hashbrown@0.14",
    "wasi@0.11",
    "zerocopy@0.7",
]
skip-tree = [
    { crate = "rand@0.8", depth = 2 },
    { crate = "windows-sys@0.48", depth = 3 },
    { crate = "windows-sys@0.52", depth = 3 },
]
