[licenses]
allow = ["MPL-2.0"]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "marmalade" },
    { allow = ["OpenSSL"], name = "ring" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "base64", version = "=0.13.1" },
    { name = "hashbrown", version = "=0.11.2" },
    { name = "syn", version = "=1.0.109" },
]
skip-tree = [
    { name = "windows-sys", version = "=0.42.0", depth = 2 },
    { name = "windows-sys", version = "=0.45.0", depth = 2 },
]

[sources]
allow-git = [
    "https://github.com/dnaka91/archer.git",
]
