[advisories]
ignore = ["RUSTSEC-2023-0052"]

[licenses]
allow = ["MPL-2.0"]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "marmalade" },
    { allow = ["OpenSSL"], name = "ring" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "base64", version = "0.13" },
    { name = "bitflags", version = "1" },
    { name = "hashbrown", version = "0.11" },
    { name = "socket2", version = "0.4" },
    { name = "syn", version = "1" },
]

[sources]
allow-git = [
    "https://github.com/dnaka91/archer.git",
]
