[licenses]
allow = []
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "marmalade", version = "*" },
]

[bans]
skip = [
    { name = "tokio-util", version = "=0.6.9" },
]
