[advisories]
ignore = [
    "RUSTSEC-2021-0136",
    "RUSTSEC-2022-0048",
]

[licenses]
allow = []
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "marmalade" },
    { allow = ["OpenSSL"], name = "ring" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "wasi", version = "=0.10.2" },
]

[sources]
allow-git = [
    "https://github.com/djc/askama.git",
    "https://github.com/dnaka91/archer.git",
]
