[licenses]
allow = ["MPL-2.0"]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "marmalade" },
    { allow = ["OpenSSL"], name = "ring" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "bitflags", version = "1" },
    { name = "hashbrown", version = "0.12" },
    { name = "indexmap", version = "1" },
    { name = "ring", version = "0.16" },
    { name = "spin", version = "0.5" },
    { name = "syn", version = "1" },
    { name = "untrusted", version = "0.7" },
]

[sources]
allow-git = [
    "https://github.com/dnaka91/archer.git",
]
