[licenses]
allow = []
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "marmalade", version = "*" },
]

[bans]
skip = [
    { name = "wasi", version = "=0.10.2" },
]

[sources]
allow-git = [
	"https://github.com/djc/askama.git",
]
