[advisories]
version = 2
ignore = ["RUSTSEC-2024-0320"]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "marmalade" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip = [
    { name = "base64", version = "0.21" },
    { name = "bitflags", version = "1" },
    { name = "hashbrown", version = "0.14" },
    { name = "sync_wrapper", version = "0.1" },
]
skip-tree = [
    { name = "windows-sys", version = "0.48", depth = 3 },
    { name = "windows-sys", version = "0.52", depth = 3 },
]
