[licenses]
allow = ["MPL-2.0"]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "marmalade" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip = [
    { name = "bitflags", version = "1" },
    { name = "hashbrown", version = "0.11" },
    { name = "hashbrown", version = "0.12" },
    { name = "indexmap", version = "1" },
    { name = "syn", version = "1" },
]
